// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 3e948003a089a0df75afab4bb949e8c4)
interface __BaseEnv_Env {
  JIRA_DB: D1Database;
  ATLASSIAN_CLIENT_ID: "configure-in-atlassian-developer-console";
  ALLOWED_ORIGINS: "https://plantuml.brosenius.se,http://localhost:5173,http://127.0.0.1:5173";
  ATLASSIAN_CLIENT_SECRET: string;
  TOKEN_ENCRYPTION_KEY: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "ATLASSIAN_CLIENT_ID" | "ALLOWED_ORIGINS" | "ATLASSIAN_CLIENT_SECRET" | "TOKEN_ENCRYPTION_KEY">
  > {}
}
